### ISSUE TITLE
Question about development

### ISSUE THREAD

**Issue by 1n5aN1aC** [thijsbekke/OctoPrint-Pushover#12]
Hello!

If I were to make a pull request adding features such as notification on start, notification of time remaining every X minutes, etc.  Would you be interested in reviewing and pulling said changes?  I think it would have to disable said features if the user does not use their own API key, as you mentioned that was an issue for you.  However, I use my own anyways, so that is not an issue for me.

If you would rather not, would you be OK with me making my own plugin, borrowing some of your pushover-interfacing code to add the sole features I am missing?  (I know it's GPL, but I'd rather still ask if you have any preferences about if it's etc.)

Thanks!

**Comment by thijsbekke** [comment]
Hello !! 

Please do, I would love too see your new features and have someone else develop at this plugin. It is a good solution to limit those new features. Below is a picture of the recent usage of this API key. The average each month is 10,000 notifications, they where so kindly that they upgraded it from 10,000 to 12,500.

<img width="896" alt="pushover" src="https://user-images.githubusercontent.com/1152678/27094223-ae363ad4-5069-11e7-89b0-f262bb28f0d9.PNG">


I will see your pull request.

**Comment by 1n5aN1aC** [comment]
Alright, I've got a couple questions about your code / code style.

1.  Is it acceptable to rearrange a couple of your methods to for example put the events in expected chronological order?
2.  To add the functionality of regular (hour by default) progress updates, is it good form to add an 'API' command to `on_api_command` and the related locations, then call that from the event / timer?  If not, where would you like me to place that functionality?

Thanks!

**Comment by thijsbekke** [comment]
Hi, 

1. Yeah it is acceptable to rearrange and move stuff. I don't have a specific standard for this project. 

2. Why wouldn't you place it there ? Why not ?

**Comment by 1n5aN1aC** [comment]
Thanks!

Anyways, I've made some progress on this, but other projects have come up first, so it may be a while.

I'll just close this issue for now, since the original question I asked has been answered.  :)
