### ISSUE TITLE
Send push message with webcam image

### ISSUE THREAD

**Issue by Nappyy** [thijsbekke/OctoPrint-Pushover#14]
Hi there,

since pushover 3.0 it supports also to send push messages with images.
It would be a cool feature if your plugin could send a webcam image of the finished print.

**Comment by jbkuma** [comment]
I concur, I started looking through the code to see if I could implement it out on my own.  It is not immediately obvious to me where I would go about adding this.

**Comment by thijsbekke** [comment]
Hey, 

That is a good idea ! I am already working on it, and it is almost done.

**Comment by thijsbekke** [comment]
Almost there.. Only have to test it before releasing it.

https://github.com/thijsbekke/OctoPrint-Pushover/tree/image

**Comment by thijsbekke** [comment]
See the new release (https://github.com/thijsbekke/OctoPrint-Pushover/releases/tag/0.2.0) 

Please let me know if it is not working !

**Comment by Nappyy** [comment]
perfect, thanks!
