### ISSUE TITLE
[Request] Send an image every X% of progress

### ISSUE THREAD

**Issue by bagobones** [thijsbekke/OctoPrint-Pushover#17]
I currently use an external method to do this, but I would love for example to send a picture every 25% or so to be reminded to check on the status of the print and quickly see if it has failed.

Using my other method that currently uses homeassistant I send notifications at 5/25/50/75/99% completion.

**Comment by bagobones** [comment]
Was rebuilding some of my automation and remembered this was still here. 

Any chance of this being implemented?

**Comment by CptanPanic** [comment]
Yes you need to make it so we can add our own API key.

**Comment by thijsbekke** [comment]
@CptanPanic In the last release (which I released a couple of minutes ago), you have the ability to obtain and enter your own API key. This opens the road to solving this issue and #25. stay tuned.

**Comment by jefft8910** [comment]
> @CptanPanic In the last release (which I released a couple of minutes ago), you have the ability to obtain and enter your own API key. This opens the road to solving this issue and #25. stay tuned.

Guess I picked up this plugin at exactly the right time - this would prevent me from needing to set up a separate plugin with periodic emails to Pushover to address this.

**Comment by markuskruse** [comment]
I will donate $50 if this request is implemented (sent through paypal or any other means that we agree on). All you others that like this, feel free to donate more than this. I will match the highest bidder (up to $200).

**Comment by JasonMillward** [comment]
I'd like to throw my hand up for this one. I'm about 60% of the way through a merge request that will allow for sending every X minutes (and every Y minutes when under the first hour).

After that I'll see if it's possible to retrieve the progress percentage, if it is it should be easy enough to trigger on X%.

**Comment by thijsbekke** [comment]
It is merged and will create a release soon. I want too ad some more events. 

Thnx

**Comment by thijsbekke** [comment]
Added more events. I will test this tomorrow on an actual 3d printer. When that is a success it will be released, thanks for the patience.

**Comment by bagobones** [comment]
Looking forward to testing it.

**Comment by thijsbekke** [comment]
In the latest release it is now possible too receive an notification every X minutes.
