### ISSUE TITLE
No notification on error

### ISSUE THREAD

**Issue by SebastianSchultz** [thijsbekke/OctoPrint-Pushover#18]
Hello,

I had a "thermal runaway" today andgot no notification.
"Print done" notification works.

**Comment by thijsbekke** [comment]
Wow, that is not good. I will look into it.

**Comment by bytefray** [comment]
Same here, just had a thermal runaway (false alarm, thankfully) and no notification was sent.

**Comment by thijsbekke** [comment]
Hey,

I think I fixed this issue. However I can not test a thermal runnaway. So here is how I test it, when printing I disconnected my temperature sensor. And that gave me an error, and with the latest release a notification. 

Default those messages are high prio, you can change this behaviour under advanced options. Can you guys confirm this ?

**Comment by bytefray** [comment]
Just installed the latest update and mistuned my PID settings so I could simulate the false alarm thermal runaway. This time, the plugin sent a high-priority Pushover alert:

"Error!! An error has occurred in the printer communication. Heating failed, system stopped! Heater_ID:0"

Looks like you fixed it. Thanks!!!

**Comment by SebastianSchultz** [comment]
Here also :)
It just works for me :)

Thank you in advance!
