### ISSUE TITLE
Customize pushover message

### ISSUE THREAD

**Issue by leftyfb** [thijsbekke/OctoPrint-Pushover#2]
I'd like to customize the message that comes from the pushover notification. At the moment they all start with "Thijs". I'd like it to say "3d printer" or "Octoprint" or something.

**Comment by thijsbekke** [comment]
Will do, as soon as I get Back Home

**Comment by thijsbekke** [comment]
@leftyfb can you try it again ? I released a new version but I never could of reproduce your bug. If it still exists can you post a screenshot ?

**Comment by leftyfb** [comment]
![img_1443](https://cloud.githubusercontent.com/assets/3206263/19486419/4e7837da-952c-11e6-89f4-64ebf27c7f69.PNG)

It's till showing:   "Thijs: Print job...."

**Comment by thijsbekke** [comment]
Found it, dumb mistake. Tonight you get a new update wit the fix. Sorry for the waiting.

**Comment by thijsbekke** [comment]
This issue is fixed in the lastest release. Please update too 0.1.4. Thnx for your patience.

https://github.com/thijsbekke/OctoPrint-Pushover/tree/0.1.4
