### ISSUE TITLE
Take photo before print ends

### ISSUE THREAD

**Issue by ikoutone** [thijsbekke/OctoPrint-Pushover#24]
> G91
G1 F1800 E-3
G1 F3000 Z10
G90
G1 X0 Y220 F1000 ; prepare for part removal
M106 S0 ; turn off cooling fan
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors

Above is my end g-code, which moves the bed to the front and this is out of the view of the camera. Would it be possible to take a photo before the move happens?

Below is a screenshot from my phone how it looks. The bed moves to right from the camera POV, so the print is not visible.

![screenshot_20181125-165657](https://user-images.githubusercontent.com/6661689/48980551-5a62f300-f0d3-11e8-88e9-3e465aa976bc.jpg)

**Comment by thijsbekke** [comment]
Hi, 

It is not possible to take a picture before the "done" event is triggered. You can include a M0 or a M226 event before the bed moves it will send a picture and then pause the printer. 

When I create such feature I will reply on this issue.
