### ISSUE TITLE
%Progress Spam

### ISSUE THREAD

**Issue by CJICantLie** [thijsbekke/OctoPrint-Pushover#31]
When using "Notify me (percent)" the plugin seems to send the notification multiple times, especially on slower prints.  

Expected behavior: 
Single notification at requested percentage.

Current behavior:
Multiple notifications occurring within requested percentage, especially on longer prints.

**Comment by thijsbekke** [comment]
Good find 👍 

I never tested this feature with longer prints, will fix it.

**Comment by thijsbekke** [comment]
@CJICantLie Sorry for the late reply. I think I fixed this issue in the latest release, can you let me know if it is not working for you ? 

https://github.com/thijsbekke/OctoPrint-Pushover/releases/tag/0.3.1
