### ISSUE TITLE
Feature Request: Notify after finishing first layer. 

### ISSUE THREAD

**Issue by CptanPanic** [thijsbekke/OctoPrint-Pushover#34]
More important for me than after stuff is heated up is that first layer is done so I can make sure it is starting good. Thanks

**Comment by npostma** [comment]
+1

**Comment by thijsbekke** [comment]
@CptanPanic in the latest release you will find a new event / notification that you can enable. It will send a notification after the first couple of layers. I Think this is sufficient for your needs; "to check if the print is starting good".

https://github.com/thijsbekke/OctoPrint-Pushover/releases/tag/0.3.1
