### ISSUE TITLE
Feature Request: Notification on startup.

### ISSUE THREAD

**Issue by CptanPanic** [thijsbekke/OctoPrint-Pushover#40]
There is already a notification for printer shutdown, but how about printer startup? It would let me know if something bad happened to octoprint and the printer restarted or such.

**Comment by thijsbekke** [comment]
Hi, 

When you want a notification when something bad happens to your printer, please enable the error notification under "avanced option". By default it is enabled. 

![image](https://user-images.githubusercontent.com/1152678/69100190-eac0e300-0a5c-11ea-9203-ef8d962d7a6d.png)

That being said, you can enable a notification on startup in the next release.

**Comment by thijsbekke** [comment]
@CptanPanic When you update this plugin through OctoPrint you can be welcomed by a notification :)
