### ISSUE TITLE
"Temperature reached" is actually "Temperature reached" AND "State: Printing"

### ISSUE THREAD

**Issue by hitmusic100** [thijsbekke/OctoPrint-Pushover#43]
thank you so much for a great plugin - have noticed the above, however.  How might I get a notification when just the Temperature is reached - thanks!

**Comment by thijsbekke** [comment]
Yes, this is a late reply sorry. 

When I have the settings like in the screenshot I get an notification when the temperature is reached.

![image](https://user-images.githubusercontent.com/1152678/83812641-2bf8a780-a6bc-11ea-82f3-2acfa5be8211.png)
