### ISSUE TITLE
Multiple Pushover accounts

### ISSUE THREAD

**Issue by alegiovannelli** [thijsbekke/OctoPrint-Pushover#44]
Is it possible to configure and send notifications to 2 different Pushover accounts? Thank you. Great job.

**Comment by quinntj** [comment]
I did this within pushover using subscriptions, you use a group key instead of a user key, then each pushover user that wants the notifications can subscribe to them.

**Comment by alegiovannelli** [comment]
Thank you, it works perfectly. Thank you!
