### ISSUE TITLE
Feature Request: notification when print pauses due to filament change 

### ISSUE THREAD

**Issue by ktartoussia** [thijsbekke/OctoPrint-Pushover#46]
Hi,

I would like to see Octoprint Pushover be able to send a notification on color change request (M600: Filament change pause). 

Thanks!

P.S. great work on the plugin. It's a life saver!

**Comment by Ruprect** [comment]
I'd like to see this as well!

**Comment by thijsbekke** [comment]
With the latest release you are now able to receive a notification when a m600 command is received. Can you let me know when it is not working as expected?

https://github.com/thijsbekke/OctoPrint-Pushover/releases/tag/0.3.7
