### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Idus** [thijsbekke/OctoPrint-Pushover#50]
Did the test and got back that the Pushover-plugin was Incompatible Python 3 Plugin

**Comment by jr-air** [comment]
Thanks for the update, but it still appears to fail the "python 3" compatibility checker. Can you recheck?

This is the plugin which checks:
https://github.com/jneilliii/OctoPrint-Python3PluginCompatibilityCheck

**Comment by thijsbekke** [comment]
For future reference: https://github.com/jneilliii/OctoPrint-Python3PluginCompatibilityCheck/issues/2

**Comment by thijsbekke** [comment]
When the pull request (https://github.com/OctoPrint/plugins.octoprint.org/pull/478) is merged the checker will pass.
