### ISSUE TITLE
Feature Request: Configure priority of scheduled notification

### ISSUE THREAD

**Issue by Yeraze** [thijsbekke/OctoPrint-Pushover#51]
When you enable the  Notifications at Interval (time or percentage), they all default to Normal priority it seems and there's no wya to change it.  I would like to drop them to "Low" priority.

**Comment by thijsbekke** [comment]
Hi,

I did ad the ability to change the priority of time and percentage. It is one option for both settings. Otherwise there will be too many settings.

It will be there with an update real soon
