### ISSUE TITLE
Webcam Image Missing

### ISSUE THREAD

**Issue by roundyuk** [thijsbekke/OctoPrint-Pushover#55]
Since the most recent update the webcam snapshot is missing from the push notification? Snapshot test within Octoprint works fine.

**Comment by merson316** [comment]
Can confirm. Started having the same issue once the recent update was installed.

**Comment by thijsbekke** [comment]
I am on it.

**Comment by roundyuk** [comment]
Thanks man!

Chris

**Comment by thijsbekke** [comment]
Sorry, the latest python 3 changes did break the picture in the notification 😞, it should be good now.

Please update to the latest version. 

https://github.com/thijsbekke/OctoPrint-Pushover/releases/tag/0.3.6

**Comment by roundyuk** [comment]
Super quick fix dude, awesome!

Thanks 😊
