### ISSUE TITLE
Support for "device"

### ISSUE THREAD

**Issue by soundstorm** [thijsbekke/OctoPrint-Pushover#9]
I don't want to spam all devices, so on my own applications I usually restrict the messages to a single device, that is relevant to this action. Would be great to have a textbox/selector for that.

**Comment by thijsbekke** [comment]
You can create a "Delivery group" in Pushover. Add your device as a member of that group and use the "Group key" instead of the "User key" in the plugin. This way you manage your devices inside of pushover. Which is the way to go. 

Hope this helps.
